export const topSongs = [
    {
        id: 1,
        title: "Stay",
        author: "The Kid LAROI, Justin Bieber",
        year: "2021",
        image: "stay.png",
        audio: "stay.mp3",
        releaseDate: "01/03/2024",
        providedBy: "JHOOM MUCSIC",
        personlikes: 672,
    },
    {
        id: 2,
        title: "Memories",
        author: "Marron 5",
        year: "2021",
        image: "memory.png",
        audio: "memory.mp3",
        releaseDate: "01/03/2024",
        providedBy: "JHOOM MUCSIC",
        personlikes: 672,
    },
    {
        id: 3,
        title: "Locked away",
        author: "R. City",
        year: " 2015",
        image: "lockaway.png",
        audio: "lockaway.mp3",
        releaseDate: "01/03/2024",
        providedBy: "JHOOM MUCSIC",
        personlikes: 672,
    },
    {
        id: 4,
        title: "Head In The Clouds",
        author: "Hayd",
        year: " 2015",
        image: "headincloud.png",
        audio: "headincloud.mp3",
        releaseDate: "01/03/2024",
        providedBy: "JHOOM MUCSIC",
        personlikes: 672,
    },
    {
        id: 5,
        title: "I'm Yours ",
        author: "Jason Mraz",
        year: " 2015",
        image: "imyour.png",
        audio: "imyour.mp3",
        releaseDate: "01/03/2024",
        providedBy: "JHOOM MUCSIC",
        personlikes: 672,
    },
    {
        id: 6,
        title: "7 Years",
        author: "Imagine Dragons",
        year: "2012",
        image: "7Years.jpg",
        audio: "7Years.mp3",
        releaseDate: "01/03/2024",
        providedBy: "JHOOM MUCSIC",
        personlikes: 672,
    },
    {
        id: 7,
        title: "Cupid",
        author: "FIFTY FIFTY (피프티피프티)",
        year: "2023",
        image: "Fifty_Fifty_-_The_Beginning_Cupid.png",
        audio: "Cupid.mp3",
        releaseDate: "01/03/2024",
        providedBy: "JHOOM MUCSIC",
        personlikes: 672,
    },
    {
        id: 8,
        title: "Symphony",
        author: "Clean Bandit",
        year: "2011",
        image: "maxresdefault.jpg",
        audio: "Symphony.mp3",
        releaseDate: "01/03/2024",
        providedBy: "JHOOM MUCSIC",
        personlikes: 672,
    },
    {
        id: 9,
        title: "double take",
        author: "Dhruv",
        year: "2018",
        image: "37b950ac9bbc378c55929d68036f6581.640x640x1.jpg",
        audio: "double_take.mp3",
        releaseDate: "01/03/2024",
        providedBy: "JHOOM MUCSIC",
        personlikes: 672,
    },
    {
        id: 10,
        title: "I Do",
        author: "911",
        year: "2022",
        image: "ido.png",
        audio: "IDO.mp3",
        releaseDate: "01/03/2024",
        providedBy: "JHOOM MUCSIC",
        personlikes: 672,
    },
    {
        id: 11,
        title: "Shape Of You",
        author: "Ed Sheeran",
        year: "2017",
        image: "SOY.png",
        audio: "ShapeOfYou.mp3",
        releaseDate: "01/03/2024",
        providedBy: "JHOOM MUCSIC",
        personlikes: 672,
    },
    {
        id: 12,
        title: "Photograph",
        author: "Ed Sheeran",
        year: "2016",
        image: "photograph.jpg",
        audio: "Photograph.mp3",
        releaseDate: "01/03/2024",
        providedBy: "JHOOM MUCSIC",
        personlikes: 672,
    },
    {
        id: 13,
        title: "Stereo Heart",
        author: "Adam Levine",
        year: "2011",
        image: "SH.jpg",
        audio: "StereoHeart.mp3",
        releaseDate: "01/03/2024",
        providedBy: "JHOOM MUCSIC",
        personlikes: 672,
    },
    {
        id: 14,
        title: "Way Back Home",
        author: "SHAUN",
        year: "2016",
        image: "WBH.jpg",
        audio: "WayBackHome.mp3",
        releaseDate: "01/03/2024",
        providedBy: "JHOOM MUCSIC",
        personlikes: 672,
    },
    {
        id: 15,
        title: "Perfect",
        author: "Ed Sheeran",
        year: "2015",
        image: "Perfect.jpg",
        audio: "Perfect.mp3",
        releaseDate: "01/03/2024",
        providedBy: "JHOOM MUCSIC",
        personlikes: 672,
    },
];

export const albums = [
    {
        id: 1,
        image: "playlist1.jpg",
        title: "How I can say I love you",
        sub_title: "The art of music",
        date: "01/03/2024",
        creator: " Hằngcute",
        like: "30K",
        imageArtist: "jason.jpg",
        artists_name: "Jackson",
    },
    {
        id: 2,
        image: "playlist2.jpg",
        title: "Love you again",
        sub_title: "The amazing of music",
        date: "3/2024",
        creator: "Hằngcute",
        like: "60K",
        imageArtist: "jason.jpg",
        artists_name: "Jackson",
    },
    {
        id: 3,
        image: "playlist3.jpg",
        title: "Relaxing music",
        sub_title: "Music for soul",
        date: "3/2024",
        creator: " Hằngcute",
        like: "50K",
        imageArtist: "jason.jpg",
        artists_name: "Jackson",
    },
    {
        id: 4,
        image: "playlist4.jpg",
        title: "For the day",
        sub_title: "Good vide ",
        date: "3/2024",
        creator: " Hằngcute",
        like: "40K",
        imageArtist: "jason.jpg",
        artists_name: "Jackson",
    },
];

export const topAlbums = [
    {
        id: 5,
        image: "playlist5.jpg",
        title: "How I can say I love you",
        sub_title: "The art of music",
        date: "01/03/2024",
        creator: " Hằngcute",
        like: "30K",
        imageArtist: "jason.jpg",
        artists_name: "Jackson",
    },
    {
        id: 6,
        image: "playlist6.jpg",
        title: "Love you again",
        sub_title: "The amazing of music",
        date: "3/2024",
        creator: " Hằngcute",
        like: "60K",
        imageArtist: "jason.jpg",
        artists_name: "Jackson",
    },
    {
        id: 7,
        image: "playlist7.jpg",
        title: "Relaxing music",
        sub_title: "Music for soul",
        date: "3/2024",
        creator: " Hằngcute",
        like: "50K",
        imageArtist: "jason.jpg",
        artists_name: "Jackson",
    },
    {
        id: 8,
        image: "playlist8.jpg",
        title: "For the day",
        sub_title: "Good vide ",
        date: "3/2024",
        creator: " Hằngcute",
        like: "40K",
        imageArtist: "jason.jpg",
        artists_name: "Jackson",
    },
];

export const allAlbums = [
    {
        id: 1,
        image: "playlist1.jpg",
        title: "How I can say I love you",
        sub_title: "The art of music",
        date: "01/03/2024",
        creator: "Hằngcute",
        like: "30K",
        imageArtist: "jason.jpg",
        artists_name: "Jackson",
    },
    {
        id: 2,
        image: "playlist2.jpg",
        title: "Love you again",
        sub_title: "The amazing of music",
        date: "3/2024",
        creator: " Hằngcute",
        like: "60K",
        imageArtist: "jason.jpg",
        artists_name: "Jackson",
    },
    {
        id: 3,
        image: "playlist3.jpg",
        title: "Relaxing music",
        sub_title: "Music for soul",
        date: "3/2024",
        creator: " Hằngcute",
        like: "50K",
        imageArtist: "jason.jpg",
        artists_name: "Jackson",
    },
    {
        id: 4,
        image: "playlist4.jpg",
        title: "For the day",
        sub_title: "Good vide ",
        date: "3/2024",
        creator: "Hằngcute ",
        like: "40K",
        imageArtist: "jason.jpg",
        artists_name: "Jackson",
    },
    {
        id: 5,
        image: "playlist5.jpg",
        title: "How I can say I love you",
        sub_title: "The art of music",
        date: "01/03/2024",
        creator: "Hằngcute",
        like: "30K",
        imageArtist: "jason.jpg",
        artists_name: "Jackson",
    },
    {
        id: 6,
        image: "playlist6.jpg",
        title: "Love you again",
        sub_title: "The amazing of music",
        date: "01/03/2024",
        creator: " Hằngcute",
        like: "60K",
        imageArtist: "jason.jpg",
        artists_name: "Jackson",
    },
    {
        id: 7,
        image: "playlist7.jpg",
        title: "Relaxing music",
        sub_title: "Music for soul",
        date: "01/03/2024",
        creator: " Hằngcute",
        like: "50K",
        imageArtist: "jason.jpg",
        artists_name: "Jackson",
    },
    {
        id: 8,
        image: "playlist8.jpg",
        title: "For the day",
        sub_title: "Good vide ",
        date: "01/03/2024",
        creator: " Hằngcute",
        like: "40K",
        imageArtist: "jason.jpg",
        artists_name: "Jackson",
    },
];

export const artists = [
    {
        id: "1",
        image: "justin.jpg",
        title: "Justin Bieber",
        sub_title: "The art of music",
    },
    {
        id: "2",
        image: "jason.jpg",
        title: "Jason Mraz",
        sub_title: "The art of music",
    },
    {
        id: "3",
        image: "rock.jpg",
        title: "R. City",
        sub_title: "The art of music",
    },
    {
        id: "4",
        image: "marron.jpg",
        title: "Marron 5",
        sub_title: "The art of music",
    },
];

export const songDeatail = [{}];
